### ISSUE TITLE
conda env yaml

### ISSUE THREAD

**Issue by sangyx** [Wuyxin/DIR-GNN#11]
I can't install packages from the requirements.txt you provided because there are some package conflicts, could you give an updated version or provide a conda env yaml (`conda env export > dir.yaml`) if you use conda?

**Comment by Wuyxin** [comment]
Hi,

You can follow [here](https://github.com/Wuyxin/DIR-GNN/blob/main/setup_env.sh) now to setup the conda environment quickly. You may want to change the cuda version 11.3 to the cuda version of your machine. 

I also uploaded `dir.yaml` for reference. Let me know if there are further issues with the env setup :)
