### ISSUE TITLE
parameters  in paper

### ISSUE THREAD

**Issue by syn13355061266** [Wuyxin/DIR-GNN#15]
Hi, I would like to ask you what are the parameters of the spurious-motif dataset in your paper, i.e. the parameters in the graph_stats(base_num) function under the path spmotif_gen/spmotif.ipynb.

**Comment by Wuyxin** [comment]
Hi the parameters we used should be the default values in the notebook file

**Comment by syn13355061266** [comment]
Thank you for your reply. I noticed that your notebook code only generates a training set of 3,000 graphs, so you just need to change it to generate a training set of 9,000 graphs under the original parameters and leave the other parameters untouched, right?

**Comment by Wuyxin** [comment]
Yes exactly!
