### ISSUE TITLE
Dataset MolHIV

### ISSUE THREAD

**Issue by smiles724** [Wuyxin/DIR-GNN#2]
Hi, thanks for sharing the code. However, I wonder whether you miss out on one of the four datasets used in your paper: the MolHIV dataset. Can you please provide some information regarding how you use it and the relevant code?

**Comment by Wuyxin** [comment]
Hi, thanks. The relevant file is still under revision as some parts are redundent. I included it as `train/molhiv_dir.py` and will update it later. I think you can refer to this file for now about using the dataset etc.

**Comment by smiles724** [comment]
thx
